import { ArrowUpRight } from "lucide-react";
import { Link } from "@/i18n/navigation";
import { YodevBrand, type YodevProduct } from "@/brand/brand";
import type { ProductLandingCopy } from "@/lib/products";
import { ProductPreview } from "./product-preview";
export function ProductLanding({ copy, appUrl, accent, locale = "fr" }: { copy: ProductLandingCopy; appUrl: string; accent: YodevProduct; locale?: "fr" | "en" }) {
 const fr = locale === "fr";
 return <div className="yd-wrap" data-product={accent}><header className="yd-intro"><p className="yd-meta">{copy.eyebrow}</p><div className="my-7 text-2xl"><YodevBrand product={accent} /></div><h1>{copy.title}</h1><p className="yd-lead">{copy.subtitle}</p><p className="yd-meta mb-7">{accent === "mail" ? fr ? "Bêta privée · Candidature et invitation" : "Private beta · Application and invitation" : fr ? "Accès limité · Disponibilité à confirmer selon votre besoin" : "Limited access · Availability confirmed for your use case"}</p><div className="yd-actions">{accent === "mail" ? <a href={`https://mail.yodev.fr/${locale}/inscription`} className="yd-button">{fr ? "Candidater à la bêta" : "Apply for the beta"}<ArrowUpRight size={16} /></a> : <Link href={{ pathname: "/contact", query: { product: accent } }} className="yd-button">{fr ? "Parlons de votre besoin" : "Discuss your needs"}<ArrowUpRight size={16} /></Link>}<a href={appUrl} className="yd-button yd-button-secondary">{fr ? "Explorer le site du produit" : "Explore the product website"}<ArrowUpRight size={16} /></a></div><ProductPreview product={accent} locale={locale} /></header><section className="yd-section"><div className="yd-section-head"><span className="yd-meta">{fr ? "L’usage" : "The use case"}</span><h2>{copy.featuresTitle}</h2></div><div className="yd-services">{copy.features.map((feature,i) => <article className="yd-service" key={feature.title}><span className="yd-meta">0{i+1}</span><div><h3>{feature.title}</h3><p>{feature.description}</p></div></article>)}</div></section><section className="yd-section"><h2>{copy.closingTitle}</h2><p className="yd-lead">{copy.closingBody}</p><Link href="/contact" className="yd-button">{fr ? "Parlons-en" : "Let’s talk"}<ArrowUpRight size={16} /></Link></section></div>;
}
